(function(){
'use strict';
var START=new Date(2026,7,17,12),END=new Date(2027,0,23,12),START_W=102,TARGET_W=85,DAY=86400000;
var WSTORE='road85.weights.v4',CSTORE='road85.waist.v1';
function $(id){return document.getElementById(id)}
function localDay(d){d=d||new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate(),12)}
function days(a,b){return Math.round((b-a)/DAY)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function parse(s){var a=s.split('-').map(Number);return new Date(a[0],a[1]-1,a[2],12)}
function plural(n){var a=Math.abs(n)%100,b=a%10;return a>10&&a<20?'дней':b===1?'день':b>=2&&b<=4?'дня':'дней'}
var TOTAL=days(START,END),pageIndex=0,pending=null;
var pages=[$('roadPage'),$('weightPage'),$('waistPage')],dots=[].slice.call(document.querySelectorAll('.dot'));
function showPage(i){
  pageIndex=(i+pages.length)%pages.length;
  pages.forEach(function(p,j){p.hidden=j!==pageIndex});
  dots.forEach(function(d,j){d.classList.toggle('on',j===pageIndex)});
  if(pageIndex===1){setTimeout(drawWeight,0)}
  if(pageIndex===2){setTimeout(drawWaist,0)}
}
$('nav').addEventListener('click',function(e){e.preventDefault();e.stopPropagation();showPage(pageIndex+1)});
function read(store){try{return JSON.parse(localStorage.getItem(store)||'[]')}catch(e){return []}}
function write(store,a){localStorage.setItem(store,JSON.stringify(a))}
function todayISO(){return iso(localDay())}
function findToday(store){return read(store).find(function(x){return x.date===todayISO()})}
function put(store,value,source){var a=read(store).filter(function(x){return x.date!==todayISO()});a.push({date:todayISO(),value:Math.round(value*100)/100,source:source});write(store,a)}
function toast(t){var el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){el.classList.remove('show')},1200)}
function manualSave(store,value,unit,draw){if(!Number.isFinite(value)||value<40||value>250)return false;var old=findToday(store);if(!old){put(store,value,'manual');draw();toast('сохранено');return true}pending={store:store,value:value,draw:draw};$('modalText').textContent='Сейчас сохранено '+Number(old.value==null?old.weight:old.value).toFixed(1)+' '+unit+'. Заменить на '+value.toFixed(1)+' '+unit+'?';$('modal').hidden=false;return true}
$('cancelReplace').addEventListener('click',function(){$('modal').hidden=true;pending=null});
$('confirmReplace').addEventListener('click',function(){if(pending){put(pending.store,pending.value,'manual');pending.draw();toast('заменено')}pending=null;$('modal').hidden=true});
function autoPut(store,value){var old=findToday(store);if(!old){put(store,value,'health-shortcut');return}if(old.source==='health-shortcut'){put(store,value,'health-shortcut')}}
function parseNumber(raw){if(!raw)return null;var t=decodeURIComponent(raw).toLowerCase().replace(',','.');var m=t.match(/-?\d+(?:\.\d+)?/);return m?{text:t,value:Number(m[0])}:null}
function acceptUrl(){var u=new URL(location.href),w=parseNumber(u.searchParams.get('weight')),c=parseNumber(u.searchParams.get('waist')),changed=false;if(w){var v=w.value;if(w.text.indexOf('lb')>-1||(!w.text.includes('kg')&&v>160))v/=2.2046226218;autoPut(WSTORE,v);u.searchParams.delete('weight');changed=true}if(c){var z=c.value;if(c.text.indexOf(' m')>-1||(!c.text.includes('cm')&&z<3))z*=100;autoPut(CSTORE,z);u.searchParams.delete('waist');changed=true}if(changed)history.replaceState(null,'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams.toString():'')+u.hash)}
acceptUrl();
function planWeight(d){return START_W+(TARGET_W-START_W)*clamp(days(START,d)/TOTAL,0,1)}
function renderRoad(){var t=localDay(),elapsed=clamp(days(START,t),0,TOTAL),p=clamp(elapsed/TOTAL*100,0,100),passed=t<START?0:elapsed;$('redfill').setAttribute('width',passed*10);var marker=$('todayArrow');if(t>=START&&t<END){marker.style.opacity='1';marker.setAttribute('transform','translate('+(elapsed*10)+' 0)')}else marker.style.opacity='0';var next=null;[].slice.call(document.querySelectorAll('.cp')).forEach(function(cp,i){var d=parse(cp.dataset.date);cp.classList.remove('past','next');if(d<t)cp.classList.add('past');if(!next&&i>0&&d>=t)next=cp});if(next){next.classList.add('next');var left=Math.max(0,days(t,parse(next.dataset.date)));next.querySelector('.count').textContent=left?left+' '+plural(left):'сегодня'}$('pct').textContent=p.toFixed(1);requestAnimationFrame(function(){var s=$('scroller'),r=$('road');s.scrollLeft=p?clamp(r.scrollWidth*p/100-s.clientWidth*.42,0,r.scrollWidth-s.clientWidth):0})}
var tip=$('tip');[].slice.call(document.querySelectorAll('.cp')).forEach(function(cp){cp.addEventListener('click',function(e){e.stopPropagation();var t=localDay(),d=parse(cp.dataset.date),w=Number(cp.dataset.weight),from=Math.max(0,days(START,d)),left=Math.max(0,days(t,d));tip.innerHTML='<b>'+w+' кг</b> · −'+(START_W-w).toFixed(1)+' кг · '+from+' '+plural(from)+' от старта · осталось '+(w-TARGET_W).toFixed(1)+' кг'+(d>=t?' · '+left+' '+plural(left):'');tip.style.left=cp.style.left;tip.classList.add('show')})});document.addEventListener('click',function(){tip.classList.remove('show')});
function weightPoints(){var a=read(WSTORE).map(function(x){return{date:x.date,value:Number(x.value==null?x.weight:x.value),source:x.source}}).filter(function(x){return Number.isFinite(x.value)&&parse(x.date)>=START});var r=[{date:'2026-08-17',value:102,source:'start'}];a.forEach(function(p){var i=r.findIndex(function(x){return x.date===p.date});if(i>=0)r[i]=p;else r.push(p)});return r.sort(function(a,b){return a.date.localeCompare(b.date)})}
function waistPoints(){return read(CSTORE).map(function(x){return{date:x.date,value:Number(x.value),source:x.source}}).filter(function(x){return Number.isFinite(x.value)&&parse(x.date)>=START}).sort(function(a,b){return a.date.localeCompare(b.date)})}
function prep(canvas){var r=canvas.getBoundingClientRect();if(r.width<20||r.height<20)return null;var dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);var ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);return{ctx:ctx,w:r.width,h:r.height}}
function drawWeight(){var z=prep($('weightChart'));if(!z)return;var ctx=z.ctx,w=z.w,h=z.h,p={l:8,r:8,t:10,b:24},pw=w-p.l-p.r,ph=h-p.t-p.b;function X(d){return p.l+clamp(days(START,d)/TOTAL,0,1)*pw}function Y(v){return p.t+(104-v)/21*ph}ctx.clearRect(0,0,w,h);[85,90,95,100].forEach(function(v){ctx.strokeStyle='rgba(255,255,255,.055)';ctx.beginPath();ctx.moveTo(p.l,Y(v));ctx.lineTo(w-p.r,Y(v));ctx.stroke();ctx.fillStyle='rgba(255,255,255,.25)';ctx.font='10px -apple-system';ctx.fillText(String(v),p.l+1,Y(v)-5)});ctx.strokeStyle='#ffd21a';ctx.lineWidth=2.2;ctx.setLineDash([7,6]);ctx.beginPath();for(var i=0;i<=TOTAL;i++){var d=new Date(START.getTime()+i*DAY),xx=X(d),yy=Y(planWeight(d));i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.stroke();ctx.setLineDash([]);var pts=weightPoints();ctx.strokeStyle='#f4f0e7';ctx.lineWidth=2.4;ctx.beginPath();pts.forEach(function(q,i){i?ctx.lineTo(X(parse(q.date)),Y(q.value)):ctx.moveTo(X(parse(q.date)),Y(q.value))});ctx.stroke();pts.forEach(function(q,i){ctx.fillStyle=i===pts.length-1&&pts.length>1?'#ff3b30':'#f4f0e7';ctx.beginPath();ctx.arc(X(parse(q.date)),Y(q.value),i===pts.length-1&&pts.length>1?3.6:2.4,0,Math.PI*2);ctx.fill()});var last=pts[pts.length-1],delta=last.value-planWeight(parse(last.date));$('latestWeight').textContent=last.value.toFixed(1)+' кг';$('latestWeightMeta').textContent=last.source==='start'?'стартовая точка':(delta>=0?'+':'')+delta.toFixed(1)+' кг от плана'}
function drawWaist(){var z=prep($('waistChart'));if(!z)return;var ctx=z.ctx,w=z.w,h=z.h,pts=waistPoints(),p={l:8,r:8,t:10,b:24},pw=w-p.l-p.r,ph=h-p.t-p.b;ctx.clearRect(0,0,w,h);if(!pts.length){ctx.fillStyle='rgba(255,255,255,.22)';ctx.font='12px -apple-system';ctx.textAlign='center';ctx.fillText('Первый замер создаст стартовую точку',w/2,h/2);ctx.textAlign='left';$('latestWaist').textContent='—';$('latestWaistMeta').textContent='нет измерений';return}var vals=pts.map(function(q){return q.value}),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals),lo=Math.floor(min-4),hi=Math.ceil(max+4),span=Math.max(8,hi-lo);function X(d){return p.l+clamp(days(START,d)/TOTAL,0,1)*pw}function Y(v){return p.t+(hi-v)/span*ph}for(var v=Math.ceil(lo/2)*2;v<=hi;v+=2){ctx.strokeStyle='rgba(255,255,255,.05)';ctx.beginPath();ctx.moveTo(p.l,Y(v));ctx.lineTo(w-p.r,Y(v));ctx.stroke();ctx.fillStyle='rgba(255,255,255,.22)';ctx.font='10px -apple-system';ctx.fillText(String(v),p.l+1,Y(v)-5)}var base=pts[0].value;ctx.strokeStyle='#ffd21a';ctx.lineWidth=1.8;ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(p.l,Y(base));ctx.lineTo(w-p.r,Y(base));ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#f4f0e7';ctx.lineWidth=2.4;ctx.beginPath();pts.forEach(function(q,i){i?ctx.lineTo(X(parse(q.date)),Y(q.value)):ctx.moveTo(X(parse(q.date)),Y(q.value))});ctx.stroke();pts.forEach(function(q,i){ctx.fillStyle=i===pts.length-1?'#ff3b30':'#f4f0e7';ctx.beginPath();ctx.arc(X(parse(q.date)),Y(q.value),i===pts.length-1?3.6:2.4,0,Math.PI*2);ctx.fill()});var last=pts[pts.length-1],delta=last.value-base;$('latestWaist').textContent=last.value.toFixed(1)+' см';$('latestWaistMeta').textContent=pts.length===1?'первый замер':(delta>0?'+':'')+delta.toFixed(1)+' см от первого замера'}
$('saveWeight').addEventListener('click',function(){var v=Number(String($('weightInput').value).replace(',','.'));if(manualSave(WSTORE,v,'кг',drawWeight))$('weightInput').value=''})
$('saveWaist').addEventListener('click',function(){var v=Number(String($('waistInput').value).replace(',','.'));if(manualSave(CSTORE,v,'см',drawWaist))$('waistInput').value=''})
$('weightInput').addEventListener('keydown',function(e){if(e.key==='Enter')$('saveWeight').click()});$('waistInput').addEventListener('keydown',function(e){if(e.key==='Enter')$('saveWaist').click()});
window.addEventListener('resize',function(){if(pageIndex===1)drawWeight();if(pageIndex===2)drawWaist()});
renderRoad();showPage(0);
})();